import { Recording } from './recordings.types';
import { Transcript } from '../transcripts/transcripts.types';

export const INITIAL_RECORDINGS: Recording[] = [
  {
    id: 'rec-501',
    callId: 'call-901',
    leadId: 'lead-101',
    leadName: 'Elena Rostova',
    company: 'Apex Robotics',
    employeeId: 'emp-1',
    employeeName: 'Sarah Jenkins',
    date: '2026-09-18 16:45',
    duration: '04:18',
    durationSeconds: 258,
    status: 'available',
    metadata: {
      callId: 'call-901',
      leadId: 'lead-101',
      leadName: 'Elena Rostova',
      company: 'Apex Robotics',
      employeeId: 'emp-1',
      employeeName: 'Sarah Jenkins',
      callDate: 'Sep 18, 2026',
      startTime: '16:45:12 UTC',
      duration: '04:18',
      durationSeconds: 258,
      direction: 'outbound',
      status: 'available',
      callOutcome: 'Interested',
      fileSize: '4.2 MB',
      audioFormat: 'Opus / WebM 48kHz',
      channels: 2,
      bitrate: '128 kbps',
      sampleRate: '48,000 Hz',
    },
    transcriptId: 'tr-501',
  },
  {
    id: 'rec-502',
    callId: 'call-902',
    leadId: 'lead-102',
    leadName: 'Marcus Vance',
    company: 'Vance Dynamics',
    employeeId: 'emp-2',
    employeeName: 'David Kim',
    date: '2026-09-18 15:30',
    duration: '03:45',
    durationSeconds: 225,
    status: 'available',
    metadata: {
      callId: 'call-902',
      leadId: 'lead-102',
      leadName: 'Marcus Vance',
      company: 'Vance Dynamics',
      employeeId: 'emp-2',
      employeeName: 'David Kim',
      callDate: 'Sep 18, 2026',
      startTime: '15:30:00 UTC',
      duration: '03:45',
      durationSeconds: 225,
      direction: 'outbound',
      status: 'available',
      callOutcome: 'Follow-up Required',
      fileSize: '3.7 MB',
      audioFormat: 'Opus / WebM 48kHz',
      channels: 2,
      bitrate: '128 kbps',
      sampleRate: '48,000 Hz',
    },
    transcriptId: 'tr-502',
  },
  {
    id: 'rec-503',
    callId: 'call-903',
    leadId: 'lead-103',
    leadName: 'Sofia Chen',
    company: 'Quantum Health',
    employeeId: 'emp-3',
    employeeName: 'Alex Rivera',
    date: '2026-09-18 14:15',
    duration: '05:32',
    durationSeconds: 332,
    status: 'available',
    metadata: {
      callId: 'call-903',
      leadId: 'lead-103',
      leadName: 'Sofia Chen',
      company: 'Quantum Health',
      employeeId: 'emp-3',
      employeeName: 'Alex Rivera',
      callDate: 'Sep 18, 2026',
      startTime: '14:15:08 UTC',
      duration: '05:32',
      durationSeconds: 332,
      direction: 'outbound',
      status: 'available',
      callOutcome: 'Converted',
      fileSize: '5.6 MB',
      audioFormat: 'Opus / WebM 48kHz',
      channels: 2,
      bitrate: '128 kbps',
      sampleRate: '48,000 Hz',
    },
    transcriptId: 'tr-503',
  },
  {
    id: 'rec-504',
    callId: 'call-904',
    leadId: 'lead-104',
    leadName: 'David Thorne',
    company: 'Thorne Logistics',
    employeeId: 'emp-1',
    employeeName: 'Sarah Jenkins',
    date: '2026-09-18 13:00',
    duration: '01:50',
    durationSeconds: 110,
    status: 'processing',
    metadata: {
      callId: 'call-904',
      leadId: 'lead-104',
      leadName: 'David Thorne',
      company: 'Thorne Logistics',
      employeeId: 'emp-1',
      employeeName: 'Sarah Jenkins',
      callDate: 'Sep 18, 2026',
      startTime: '13:00:22 UTC',
      duration: '01:50',
      durationSeconds: 110,
      direction: 'outbound',
      status: 'processing',
      callOutcome: 'Follow-up Required',
      fileSize: '1.8 MB',
      audioFormat: 'Pending Ingestion',
      channels: 2,
    },
  },
  {
    id: 'rec-505',
    callId: 'call-905',
    leadId: 'lead-105',
    leadName: 'Amara Okafor',
    company: 'Solaris Fintech',
    employeeId: 'emp-2',
    employeeName: 'David Kim',
    date: '2026-09-17 17:10',
    duration: '00:45',
    durationSeconds: 45,
    status: 'failed',
    metadata: {
      callId: 'call-905',
      leadId: 'lead-105',
      leadName: 'Amara Okafor',
      company: 'Solaris Fintech',
      employeeId: 'emp-2',
      employeeName: 'David Kim',
      callDate: 'Sep 17, 2026',
      startTime: '17:10:14 UTC',
      duration: '00:45',
      durationSeconds: 45,
      direction: 'outbound',
      status: 'failed',
      callOutcome: 'Line Disconnected',
      audioFormat: 'Corrupt SIP packet payload',
      channels: 1,
    },
  },
  {
    id: 'rec-506',
    callId: 'call-906',
    leadId: 'lead-106',
    leadName: 'Liam O\'Connor',
    company: 'Cascade Retail',
    employeeId: 'emp-4',
    employeeName: 'Emily Taylor',
    date: '2026-09-17 11:20',
    duration: '02:10',
    durationSeconds: 130,
    status: 'unavailable',
    metadata: {
      callId: 'call-906',
      leadId: 'lead-106',
      leadName: 'Liam O\'Connor',
      company: 'Cascade Retail',
      employeeId: 'emp-4',
      employeeName: 'Emily Taylor',
      callDate: 'Sep 17, 2026',
      startTime: '11:20:00 UTC',
      duration: '02:10',
      durationSeconds: 130,
      direction: 'outbound',
      status: 'unavailable',
      callOutcome: 'No Answer',
      audioFormat: 'Session Not Recorded (User Opt-Out)',
      channels: 0,
    },
  },
];

export const INITIAL_TRANSCRIPTS: Record<string, Transcript> = {
  'tr-501': {
    id: 'tr-501',
    recordingId: 'rec-501',
    callId: 'call-901',
    leadName: 'Elena Rostova',
    employeeName: 'Sarah Jenkins',
    company: 'Apex Robotics',
    language: 'English (US)',
    duration: '04:18',
    messages: [
      {
        id: 'msg-101',
        speaker: 'Sarah Jenkins',
        speakerType: 'employee',
        timestamp: '00:02',
        timestampSeconds: 2,
        text: 'Hi Elena, this is Sarah Jenkins calling from FRIDAY Sales Core. Thank you for connecting with us regarding autonomous telecommunications for Apex Robotics.',
      },
      {
        id: 'msg-102',
        speaker: 'Elena Rostova',
        speakerType: 'lead',
        timestamp: '00:11',
        timestampSeconds: 11,
        text: 'Hello Sarah! Yes, thank you for reaching out. We are expanding our automation facility in Munich and our outbound telemetry needs are scaling rapidly.',
      },
      {
        id: 'msg-103',
        speaker: 'Sarah Jenkins',
        speakerType: 'employee',
        timestamp: '00:24',
        timestampSeconds: 24,
        text: 'That aligns directly with what we observed in your architecture brief. When your field reps initiate hardware consultations, how are call records and transcripts currently synchronized with your internal ERP?',
      },
      {
        id: 'msg-104',
        speaker: 'Elena Rostova',
        speakerType: 'lead',
        timestamp: '00:41',
        timestampSeconds: 41,
        text: 'Right now it is fragmented. Representatives manually type brief summaries into our CRM, but we have zero verifiable audio recordings and no searchable verbatim transcriptions.',
      },
      {
        id: 'msg-105',
        speaker: 'Sarah Jenkins',
        speakerType: 'employee',
        timestamp: '01:02',
        timestampSeconds: 62,
        text: 'Understood. That introduces significant compliance liability and information loss. With FRIDAY, dual-channel audio is stored with millisecond-accurate speaker diarization immediately upon session conclusion.',
      },
      {
        id: 'msg-106',
        speaker: 'Elena Rostova',
        speakerType: 'lead',
        timestamp: '01:25',
        timestampSeconds: 85,
        text: 'That would be a massive efficiency unlock. Can we jump directly to specific topics or keywords across historical calls?',
      },
      {
        id: 'msg-107',
        speaker: 'Sarah Jenkins',
        speakerType: 'employee',
        timestamp: '01:38',
        timestampSeconds: 98,
        text: 'Precisely. You can search any keyword or phrase, jump directly to that timestamp, and scrub the audio player in unison with the highlighted dialogue.',
      },
      {
        id: 'msg-108',
        speaker: 'Elena Rostova',
        speakerType: 'lead',
        timestamp: '02:05',
        timestampSeconds: 125,
        text: 'What about data privacy and retention policies for German industrial customers? We require strict SOC2 and GDPR compliance.',
      },
      {
        id: 'msg-109',
        speaker: 'Sarah Jenkins',
        speakerType: 'employee',
        timestamp: '02:22',
        timestampSeconds: 142,
        text: 'All payloads are encrypted at rest with customer-managed keys and zero third-party telemetry leakage. We can provide your security team with our comprehensive compliance dossier today.',
      },
      {
        id: 'msg-110',
        speaker: 'Elena Rostova',
        speakerType: 'lead',
        timestamp: '02:49',
        timestampSeconds: 169,
        text: 'Excellent. Please send that over. Let us schedule an executive pilot with our VP of Engineering next Tuesday at 10 AM CET.',
      },
      {
        id: 'msg-111',
        speaker: 'Sarah Jenkins',
        speakerType: 'employee',
        timestamp: '03:12',
        timestampSeconds: 192,
        text: 'I have marked Tuesday at 10:00 AM CET on our calendar. I will dispatch the technical briefing packet and invite right away.',
      },
      {
        id: 'msg-112',
        speaker: 'Elena Rostova',
        speakerType: 'lead',
        timestamp: '03:40',
        timestampSeconds: 220,
        text: 'Wonderful. Appreciate your thoroughness, Sarah. Looking forward to speaking next week.',
      },
      {
        id: 'msg-113',
        speaker: 'Sarah Jenkins',
        speakerType: 'employee',
        timestamp: '04:02',
        timestampSeconds: 242,
        text: 'Thank you Elena, have a great rest of your day. Goodbye.',
      },
    ],
  },
  'tr-502': {
    id: 'tr-502',
    recordingId: 'rec-502',
    callId: 'call-902',
    leadName: 'Marcus Vance',
    employeeName: 'David Kim',
    company: 'Vance Dynamics',
    language: 'English (US)',
    duration: '03:45',
    messages: [
      {
        id: 'msg-201',
        speaker: 'David Kim',
        speakerType: 'employee',
        timestamp: '00:02',
        timestampSeconds: 2,
        text: 'Hello Marcus, David Kim here from FRIDAY. Following up on your evaluation of enterprise telephony integration.',
      },
      {
        id: 'msg-202',
        speaker: 'Marcus Vance',
        speakerType: 'lead',
        timestamp: '00:15',
        timestampSeconds: 15,
        text: 'Hi David. We reviewed your initial documentation. The latency benchmarks look solid, but our legal team had concerns regarding audio retention policies.',
      },
      {
        id: 'msg-203',
        speaker: 'David Kim',
        speakerType: 'employee',
        timestamp: '00:35',
        timestampSeconds: 35,
        text: 'I can address that directly. FRIDAY supports granular retention schedules from 30 days up to 7 years with automated cryptographic purging.',
      },
      {
        id: 'msg-204',
        speaker: 'Marcus Vance',
        speakerType: 'lead',
        timestamp: '01:05',
        timestampSeconds: 65,
        text: 'That will satisfy our compliance officers. Can you provide a custom addendum reflecting those retention timelines?',
      },
      {
        id: 'msg-205',
        speaker: 'David Kim',
        speakerType: 'employee',
        timestamp: '01:30',
        timestampSeconds: 90,
        text: 'Absolutely. I will have our enterprise contracts desk issue the retention addendum by close of business today.',
      },
      {
        id: 'msg-206',
        speaker: 'Marcus Vance',
        speakerType: 'lead',
        timestamp: '02:15',
        timestampSeconds: 135,
        text: 'Great. Once legal clears that, we will execute the enterprise agreement.',
      },
      {
        id: 'msg-207',
        speaker: 'David Kim',
        speakerType: 'employee',
        timestamp: '02:50',
        timestampSeconds: 170,
        text: 'Fantastic Marcus. I will follow up via email with the paperwork attached shortly.',
      },
      {
        id: 'msg-208',
        speaker: 'Marcus Vance',
        speakerType: 'lead',
        timestamp: '03:20',
        timestampSeconds: 200,
        text: 'Sounds like a plan. Thank you David.',
      },
    ],
  },
  'tr-503': {
    id: 'tr-503',
    recordingId: 'rec-503',
    callId: 'call-903',
    leadName: 'Sofia Chen',
    employeeName: 'Alex Rivera',
    company: 'Quantum Health',
    language: 'English (US)',
    duration: '05:32',
    messages: [
      {
        id: 'msg-301',
        speaker: 'Alex Rivera',
        speakerType: 'employee',
        timestamp: '00:03',
        timestampSeconds: 3,
        text: 'Good morning Dr. Chen, Alex Rivera calling from FRIDAY regarding Quantum Health\'s patient communication deployment.',
      },
      {
        id: 'msg-302',
        speaker: 'Sofia Chen',
        speakerType: 'lead',
        timestamp: '00:18',
        timestampSeconds: 18,
        text: 'Good morning Alex. We conducted our internal security review and our board has formally approved the pilot rollout.',
      },
      {
        id: 'msg-303',
        speaker: 'Alex Rivera',
        speakerType: 'employee',
        timestamp: '00:40',
        timestampSeconds: 40,
        text: 'That is tremendous news Sofia! We have already configured your dedicated sandbox tenant with HIPAA-grade encryption.',
      },
      {
        id: 'msg-304',
        speaker: 'Sofia Chen',
        speakerType: 'lead',
        timestamp: '01:12',
        timestampSeconds: 72,
        text: 'Wonderful. Our technical integration team will need API documentation and webhook endpoints by Monday morning.',
      },
      {
        id: 'msg-305',
        speaker: 'Alex Rivera',
        speakerType: 'employee',
        timestamp: '01:45',
        timestampSeconds: 105,
        text: 'Everything will be provisioned today, including Sandbox API keys and direct access to our solutions engineering team.',
      },
      {
        id: 'msg-306',
        speaker: 'Sofia Chen',
        speakerType: 'lead',
        timestamp: '02:30',
        timestampSeconds: 150,
        text: 'We are very excited about the productivity gains for our clinical staff. Let us schedule onboarding for Wednesday.',
      },
      {
        id: 'msg-307',
        speaker: 'Alex Rivera',
        speakerType: 'employee',
        timestamp: '03:15',
        timestampSeconds: 195,
        text: 'Onboarding is locked in for Wednesday. Thank you for your partnership Sofia!',
      },
    ],
  },
};

class RecordingsDataStore {
  private recordings: Recording[] = [...INITIAL_RECORDINGS];
  private transcripts: Record<string, Transcript> = { ...INITIAL_TRANSCRIPTS };
  private listeners: Set<() => void> = new Set();

  getRecordings(): Recording[] {
    return [...this.recordings];
  }

  getRecordingById(id: string): Recording | undefined {
    return this.recordings.find((r) => r.id === id);
  }

  getRecordingByCallId(callId: string): Recording | undefined {
    return this.recordings.find((r) => r.callId === callId);
  }

  getTranscriptById(id: string): Transcript | undefined {
    return this.transcripts[id];
  }

  getTranscriptByRecordingId(recordingId: string): Transcript | undefined {
    return Object.values(this.transcripts).find((t) => t.recordingId === recordingId);
  }

  getTranscriptByCallId(callId: string): Transcript | undefined {
    return Object.values(this.transcripts).find((t) => t.callId === callId);
  }

  subscribe(listener: () => void): () => void {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  }

  private notify() {
    this.listeners.forEach((cb) => cb());
  }
}

export const recordingsStore = new RecordingsDataStore();
